# Sets up the runtime paths (RPATH) for Unix-like systems

file(RELATIVE_PATH INSTALL_PREFIX_FROM_BIN "${CMAKE_INSTALL_PREFIX}/${BIN_INSTALL_DIR}" "${CMAKE_INSTALL_PREFIX}")

if(UNIX)
	set(CMAKE_SKIP_BUILD_RPATH FALSE)
	set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
	set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-z,origin")
	set(CMAKE_INSTALL_RPATH "\$ORIGIN/${INSTALL_PREFIX_FROM_BIN}${LIB_INSTALL_DIR}")
	set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
endif()
